# Use container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.stack/

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # test directory
  - mkdir -p $TRAVIS_BUILD_DIR/test-output
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

# coveralls.io coverage reports
# after_script:
#   - "cabal install hpc-coveralls"
#   - "hpc-coveralls count-von-count-tests --exclude-dir=tests --exclude-dir=src/Gyrid --display-report"

notifications:
  email: # false
    recipients:
      - graham@fatlazycat.com
    # on_success: [always|never|change] # default: change
    on_success: always # default: change
    on_failure: always # default: always
