language: haskell

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

# addons:
#   apt:
#     sources:
#     - hvr-ghc
#     packages:
#     - ghc-7.10.3
#     - libgmp-dev

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:/opt/ghc/7.10.3/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

# coveralls.io coverage reports
# after_script:
#   - "cabal install hpc-coveralls"
#   - "hpc-coveralls count-von-count-tests --exclude-dir=tests --exclude-dir=src/Gyrid --display-report"

notifications:
  email: # false
    recipients:
      - graham@fatlazycat.com
    # on_success: [always|never|change] # default: change
    on_success: always # default: change
    on_failure: always # default: always
